# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Firebase Test Lab Testing'
description: 'Create a test on Firebase Test Lab'
inputs:
  credentials_json:
    description: 'The Google Cloud JSON service account key to use for authentication.'
    required: false
  workload_identity_provider:
    description: 'The full identifier of the Workload Identity Provider, including the project number, pool name, and provider name.'
    required: false
  service_account:
    description: 'Email address or unique identifier of the Google Cloud service account. Required if "workload_identity_provider" is specified.'
    required: false
  arg_groups:
    description: 'Arguments in a YAML-formatted argument file. Separate by ";".'
    required: false
  testapp_dir:
    description: 'Testapps under this dir that will be tested.'
    required: false
  test_type:
    description: 'One of the following test types: xctest, robo, instrumentation, game-loop.'
    required: false
  test_devices:
    description: 'Device model used for testing. Separate by ";".'
    required: false
  timeout:
    description: 'Timeout for one FTL test.'
    default: '600s'
    required: false
  additional_flags:
    description: 'Additional flags and values that may be used. e.g. --xcode-version=11.3.'
    required: false
  max_attempts:
    description: 'Max retries when test on FTL failed.'
    default: 1
    required: false
  validator:
    description: '[Experimental] Path of customized python script that validate one game-loop test result.'
    required: false
  project_id:
    description: 'Firebase Project ID.'
    required: false
outputs:
  test_summary:
    description: "FTL Test summary in the JSON format"
    value: ${{ steps.ftl_test.outputs.test_summary }}

runs:
  using: 'composite'
  steps:
    # Setup GCould Env if account infomation was provided
    - uses: 'google-github-actions/auth@v0'
      if: (inputs.workload_identity_provider && inputs.service_account) || inputs.credentials_json
      with:
        credentials_json: '${{ inputs.credentials_json }}'
        workload_identity_provider: '${{ inputs.workload_identity_provider }}'
        service_account: '${{ inputs.service_account }}'
    - uses: google-github-actions/setup-gcloud@v0
      if: (inputs.workload_identity_provider && inputs.service_account) || inputs.credentials_json
      with:
        install_components: 'beta'
    - id: ftl_test
      shell: bash
      run: |
        test_result=$(python $GITHUB_ACTION_PATH/trigger_ftl_tests.py --arg_groups="${{ inputs.arg_groups }}" --testapp_dir="${{ inputs.testapp_dir }}" --test_type="${{ inputs.test_type }}" --timeout="${{ inputs.timeout }}" --test_devices="${{ inputs.test_devices }}" --additional_flags="${{ inputs.additional_flags }}" --max_attempts="${{ inputs.max_attempts }}" --validator="${{ inputs.validator }}")
        
        # first character in test_result is the exit code (0 or 1); the rest are the JSON format test summary.
        if [[ ! -z ${test_result} ]]; then
          echo "::set-output name=test_summary::$(echo ${test_result:2})"
          exit $(echo ${test_result:0:1})
        else
          exit 1
        fi
