name: 'Firebase Test Lab Testing'
description: 'Create a test on Firebase Test Lab'
inputs:
  arg_files:
    description: 'Arguments in a YAML-formatted argument file. Separate by ";"'
    required: false
  testapp_dir:
    description: 'Testapps under this dir that will be uploaded.'
    required: false
  test_type:
    description: 'One of the following test types: xctest, robo, instrumentation, game-loop.'
    required: false
  device:
    description: 'Device model used for testing. Separate by ";"'
    required: false
  timeout:
    description: 'Timeout for one ftl test.'
    default: '600s'
    required: false
  additional_flags:
    description: 'Additional flags that may be used. e.g. --xcode-version'
    required: false
  project_id:
    description: 'Firebase Project ID'
    required: false
outputs:
  test_summary:
    description: "FTL Test summary in JSON formats"
    value: ${{ steps.ftl_test.outputs.test_summary }}
runs:
  using: 'composite'
  steps:
    - uses: 'google-github-actions/auth@v0'
      if: (env.WORKLOAD_IDENTITY_PROVIDER && env.FIREBASE_SERVICE_ACCOUNT) || env.FIREBASE_SERVICE_ACCOUNT_CREDENTIALS
      with:
        credentials_json: '${{ env.FIREBASE_SERVICE_ACCOUNT_CREDENTIALS }}'
        workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ env.FIREBASE_SERVICE_ACCOUNT }}'
    - uses: google-github-actions/setup-gcloud@v0
      if: (env.WORKLOAD_IDENTITY_PROVIDER && env.FIREBASE_SERVICE_ACCOUNT) || env.FIREBASE_SERVICE_ACCOUNT_CREDENTIALS
      with:
        install_components: 'beta'
    - id: ftl_test
      shell: bash
      run: |
        test_result=$(python $GITHUB_ACTION_PATH/trigger_ftl_tests.py --arg_files "${{ inputs.arg_files }}" --testapp_dir "${{ inputs.testapp_dir }}" --test_type "${{ inputs.test_type }}" --timeout "${{ inputs.timeout }}" --additional_flags "${{ inputs.additional_flags }}")
        if [[ ! -z ${test_result} ]]; then
          echo "::set-output name=test_summary::$(echo ${test_result:2})"
          exit $(echo ${test_result:0:1})
        else
          exit 1
        fi
