name: 'Firebase Test Lab Testing'
description: 'Create a test on Firebase Test Lab'
inputs:
  testapp_dir:
    description: 'Testapps under this  dir that will be uploaded.'
    required: true
  test_type:
    description: 'Testapps under this  dir that will be uploaded.'
    required: true
  device:
    description: 'Device model used for testing'
    required: false
  credentials_json:
    description: 'credentials_json used for gcloud auth'
    required: false
  project_id:
    description: 'Firebase Project ID'
    required: false

outputs:
  ftl_links:
    description: "Links of FTL Tests"
    value: ${{ steps.ftl_test.outputs.ftl_links }}

runs:
  using: 'composite'
  steps:
    # `required` does not work as expected so a validation is needed.
    # `required` issue:https://github.com/actions/runner/issues/1070
  - name: Validate inputs
    shell: bash
    run: |
      [[ "${{ inputs.testapp_dir }}" ]] || { echo "testapp_dir is empty" ; exit 1; }
      [[ "${{ inputs.test_type }}" ]] || { echo "test_type is empty" ; exit 1; }
  - name: Setup python
    uses: actions/setup-python@v2
    with:
      python-version: 3.7
  - name: Install python deps
    shell: bash
    run: |
      pip install -r ${{ github.action_path }}/python_requirements.txt
  - id: 'auth'
    if: ${{ inputs.credentials_json }} != ''
    name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ inputs.credentials_json }}'
  - name: 'Set up Cloud SDK'
    if: ${{ inputs.credentials_json }} != ''
    uses: google-github-actions/setup-gcloud@v0
  - id: ftl_test
    shell: bash
    run: |
      echo "::set-output name=ftl_links::$(python ${{ github.action_path }}/trigger_ftl_tests.py --testapp_dir "${{ inputs.testapp_dir }}" --test_type "${{ inputs.test_type }}" )"
