name: 'Generate NOTICES'
description: 'Create a test on Firebase Test Lab'
inputs:
  testapp-dir:
    description: 'Testapps under this  dir that will be uploaded.'
    required: true
  key_file:
    description: 'Key file to access GCP service account.'
    required: true
  device:
    description: 'Device model used for testing'
    required: false
  device_version:
    description: 'Device version, e.g. 14.7, for ios version'
    required: false
outputs:
  notices_contents:
    description: 'contents of notices'
runs:
  using: 'composite'
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.7'
  - name: Set up Google Cloud SDK
    uses: google-github-actions/setup-gcloud@v0
  - name: Install dependencies
    run: |
      cd "${{ github.action_path }}"
      pip install -r requirements.txt
    shell: bash
  - name: FTL Test
    run: |
      cd "${{ github.action_path }}"
      python triger_ftl_tests.py \
      --testapp_dir "${{ inputs.testapp-dir }}" \
      --key_file "${{ inputs.key_file }}" \
      --ios_model "${{ inputs.device }}" \
      --ios_version "${{ inputs.device_version }}"
    shell: bash
