name: TestWorkflows

on:
  pull_request

jobs:
  test:
    name: test
    runs-on: macOS
    steps:
      - name: ftl-tests
        uses: google-github-actions/ftl-test-lab
      - name: test
        run: |
          echo "Hello world"

     
